language: go

go:
  - 1.11
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install

script:
  - gometalinter.v2 --config=gometalinter-ci.json ./...
  - go test -v -race ./...

after_success:
  - test "$TRAVIS_GO_VERSION" = "1.11" && goveralls -service=travis-ci
